site_name: VenafiTppPS
repo_url: https://github.com/gdbarron/VenafiTppPS
site_author: Greg Brownstein
edit_uri: edit/master/docs/
theme: readthedocs
copyright: ""
pages:
  - Home: index.md
  - Release Notes: RELEASE.md
  - Change Log: ChangeLog.md
  - Functions:
    - Add-TppCertificateAssociation: functions/Add-TppCertificateAssociation.md
    - ConvertTo-TppGuid: functions/ConvertTo-TppGuid.md
    - ConvertTo-TppPath: functions/ConvertTo-TppPath.md
    - Find-TppCertificate: functions/Find-TppCertificate.md
    - Find-TppIdentity: functions/Find-TppIdentity.md
    - Find-TppObject: functions/Find-TppObject.md
    - Get-TppAttribute: functions/Get-TppAttribute.md
    - Get-TppCertificate: functions/Get-TppCertificate.md
    - Get-TppCertificateDetail: functions/Get-TppCertificateDetail.md
    - Get-TppCustomField: functions/Get-TppCustomField.md
    - Get-TppIdentityAttribute: functions/Get-TppIdentityAttribute.md
    - Get-TppObject: functions/Get-TppObject.md
    - Get-TppPermission: functions/Get-TppPermission.md
    - Get-TppSystemStatus: functions/Get-TppSystemStatus.md
    - Get-TppVersion: functions/Get-TppVersion.md
    - Get-TppWorkflowTicket: functions/Get-TppWorkflowTicket.md
    - Invoke-TppCertificateRenewal: functions/Invoke-TppCertificateRenewal.md
    - Move-TppObject: functions/Move-TppObject.md
    - New-TppCapiApplication: functions/New-TppCapiApplication.md
    - New-TppCertificate: functions/New-TppCertificate.md
    - New-TppObject: functions/New-TppObject.md
    - New-TppPolicy: functions/New-TppPolicy.md
    - New-TppSession: functions/New-TppSession.md
    - Read-TppLog: functions/Read-TppLog.md
    - Remove-TppCertificate: functions/Remove-TppCertificate.md
    - Remove-TppCertificateAssociation: functions/Remove-TppCertificateAssociation.md
    - Rename-TppObject: functions/Rename-TppObject.md
    - Revoke-TppCertificate: functions/Revoke-TppCertificate.md
    - Set-TppAttribute: functions/Set-TppAttribute.md
    - Set-TppPermission: functions/Set-TppPermission.md
    - Set-TppWorkflowTicketStatus: functions/Set-TppWorkflowTicketStatus.md
    - Test-TppIdentity: functions/Test-TppIdentity.md
    - Test-TppObject: functions/Test-TppObject.md
    - Write-TppLog: functions/Write-TppLog.md

